### ISSUE TITLE
CSS Variables

### ISSUE THREAD

**Issue by endless-shining** [dimalovesbomb/JSdiploma#3]
[Тут ](https://github.com/dimalovesbomb/JSdiploma/blob/b05d4afee1f70b7ab64c426ead8624fe7822bcf1/src/css/master.css#L78) и в аналогичных местах стоит использовать CSS переменные, т.к. ты уже их используешь. Выглядеть будет чище.

**Comment by dimalovesbomb** [comment]
Сделал!
Спасибо :)
