### ISSUE TITLE
Имена классов

### ISSUE THREAD

**Issue by endless-shining** [dimalovesbomb/JSdiploma#4]
[Никуда не годится](https://github.com/dimalovesbomb/JSdiploma/blob/b05d4afee1f70b7ab64c426ead8624fe7822bcf1/src/components/preview-item.js#L21). Если и использовать БЭМ, то только по [правилам](https://ru.bem.info/methodology/naming-convention/), иначе больше бед будет.

**Comment by dimalovesbomb** [comment]
Исправил имена классов
